import { Component, effect, inject, Input, OnChanges, SimpleChanges } from '@angular/core';
import { EChartsOption, EChartsType } from 'echarts';
import { NgxEchartsDirective, provideEcharts } from 'ngx-echarts';
import { DifferenceItem, SankeyData, SYSTEM_PREFIX } from '../../models';
import { DataService } from '../../../services/data.service';
import { ColorService } from '../../../services/color.service';
import { CommonModule, CurrencyPipe } from '@angular/common';
import { MatChipsModule } from '@angular/material/chips';
import { parseLocaleStringToNumber, removeSystemPrefix } from '../../../utils/utils';
import { MatButtonModule } from '@angular/material/button';
import { DialogsService } from '../../../services/dialogs.service';
import { CurrencyService } from '../../../services/currency.service';
import { BaseChartComponent } from '../../../base-components/base-chart/base-chart.component';
import { UiService } from '../../../services/ui.service';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';


@Component({
  selector: 'app-sankey-chart',
  standalone: true,
  imports: [NgxEchartsDirective, CommonModule, MatChipsModule, MatButtonModule,
    MatIconModule,
    MatTooltipModule
  ],
  providers: [
    provideEcharts(),
    CurrencyPipe
  ],
  templateUrl: './sankey-chart.component.html',
  styleUrl: './sankey-chart.component.scss'
})
export class SankeyChartComponent extends BaseChartComponent implements OnChanges {

  /** Chart data input */
  @Input() sankeyData: SankeyData
  @Input() remainingBalance: string = '-'
  @Input() monthInsights: DifferenceItem[] = []


  /** Chart Configs input */
  @Input() chartHeight: string = '75vh'
  @Input() orientation: 'horizontal' | 'vertical' = 'horizontal'
  @Input() showTooltip: boolean = true
  @Input() allowInteractiveEdit: boolean = true
  @Input() showInsights: boolean = true


  dataService = inject(DataService)
  dialogService = inject(DialogsService)
  currencyPipe = inject(CurrencyPipe)
  currencyService = inject(CurrencyService)
  uiService = inject(UiService)

  sankeyOption: EChartsOption = this.getBaseChartOptions()
  sankeyMerge: EChartsOption = {}

  /** Drag threshold.
   * If the mouse movement under this threshold, it will be considered as a click event.
   * 
   * Purpose: 
   * To add some 'forgiveness' to the click event. If the threshold is 0, the mouse must be perfectly still to trigger a click event,
   * which is sometimes hard to trigger the click event.
   * 
   * Set threshold higher means if user wants to drag, they must drag more than this threshold in order to register
   * a drag event. Or else it'll be considered as a click event.
   */
  dragThreshold: number = 5;

  constructor() {
    super();
    effect(() => {
      this.updateSankeyChart();
    });
  }


  override onChartInit(chart: EChartsType): void {
    super.onChartInit(chart);

    if (!this.allowInteractiveEdit) {
      return
    }
  
    let isDragging = false;
    let startX = 0;
    let startY = 0;
  
    chart.on('mousedown', (params: any) => {
      if (params.componentType === 'series' && params.seriesType === 'sankey' && params.dataType === 'node') {
        // Capture starting mouse position
        const event = params.event.event;
        startX = event.clientX;
        startY = event.clientY;
        isDragging = false;
      }
    });
  
    chart.on('mousemove', (params: any) => {
      if (params.componentType === 'series' && params.seriesType === 'sankey' && params.dataType === 'node') {
        // Check if mouse movement exceeds a threshold
        const event = params.event.event;
        const dx = Math.abs(event.clientX - startX);
        const dy = Math.abs(event.clientY - startY);
        if (dx > this.dragThreshold || dy > this.dragThreshold) {
          isDragging = true;
        }
      }
    });
  
    chart.on('mouseup', (params: any) => {
      if (
        params.componentType === 'series' &&
        params.seriesType === 'sankey' &&
        params.dataType === 'node' &&
        !isDragging
      ) {
        if (!this.dataService.nonAllowedNames.includes(params.data.name)) {
          this.dialogService.openInsertIntoDialog(params.data);
        } else {
          this.uiService.showSnackBar(
            `You are not allowed to modify this entry, since it's generated by the system.`,
            'Close',
            5000
          );
        }
      }
    });
  }


  getBaseChartOptions(): EChartsOption {
    return {
      animation: true,
      tooltip: {
        trigger: 'item',
        position: 'top',
        triggerOn: 'mousemove',
        backgroundColor: this.colorService.isDarkMode() ? this.colorService.darkBackgroundSecondary : this.colorService.lightBackgroundPrimary,
        textStyle: {
          color: this.colorService.isDarkMode() ? this.colorService.darkTextPrimary : this.colorService.lightTextPrimary,
        },
        formatter: (params: any) => {
          if (params.dataType === 'node') {
            const nodeName = removeSystemPrefix(params.data.name);
            return `${nodeName}: <strong>${this.currencyPipe.transform(params.data.value, this.currencyService.getSelectedCurrency())}</strong>`;
          } else {
            const source = params.data.source ? removeSystemPrefix(params.data.source) : '';
            const target = params.data.target ? removeSystemPrefix(params.data.target) : '';
            return `${source} → ${target}: <strong>${this.currencyPipe.transform(params.data.value, this.currencyService.getSelectedCurrency())}</strong>`;
          }
        }
      },
      toolbox: {
        right: 20,
        feature: {
          saveAsImage: {
            name: `Financial Flow Sankey_${this.dataService.getTodaysDate()}`,
            backgroundColor: this.colorService.isDarkMode() ? this.colorService.darkBackgroundPrimary : this.colorService.lightBackgroundPrimary,
          },
        },
      },
      series: [
      ]
    }
  }


  ngOnChanges(changes: SimpleChanges): void {
    if (changes && changes['sankeyData']) {
      this.updateSankeyChart()
    }

    if (changes && changes['orientation']) {
      this.updateSankeyChart()
    }
  }

  updateSankeyChart() {
    const isDarkMode = this.colorService.isDarkMode(); // Call the signal

    this.sankeyMerge = {
      ...this.getBaseChartOptions(),
      series: [
        {
          nodeAlign: 'left',
          type: 'sankey',
          data: this.sankeyData.nodes,
          links: this.sankeyData.links,
          emphasis: { focus: 'adjacency' },
          orient: this.orientation,
          label: {
            position: this.orientation === 'horizontal' ? 'right' : 'top',
            fontSize: 12,
            color: isDarkMode ? this.colorService.darkTextPrimary : this.colorService.lightTextPrimary,
            // Use rich text for formatting
            rich: {
              bold: {
                fontWeight: 'bold',
                fontSize: 12,
                color: isDarkMode ? this.colorService.darkTextPrimary : this.colorService.lightTextPrimary,
              },
              normal: {
                fontSize: 12,
                color: isDarkMode ? this.colorService.darkTextPrimary : this.colorService.lightTextPrimary,
              }
            },
            formatter: (params: any) => {
              const nodeName = removeSystemPrefix(params.name); // Remove system prefix
              return [
                `{bold|${nodeName}}`, // Bold name
                `{normal|${params.value.toLocaleString('en-US')}}`, // Normal value
              ].join('\n'); // Join with a newline
            }
          },
          labelLayout: {
            hideOverlap: true,
          },
          nodeGap: 28,
          lineStyle: { color: 'gradient', curveness: 0.5 }
        }
      ]
    }
  }

  


  //#region Helper Functions
  isPositiveBalance(): boolean {
    const balanceNumber = parseLocaleStringToNumber(this.remainingBalance);
    return balanceNumber >= 0;
  }

  parseLocaleStringToNumber(value: string): number {
    return parseLocaleStringToNumber(value);
  }

  getBalanceClass(): string {
    return this.isPositiveBalance() ? 'positive-balance' : 'negative-balance';
  }

  removeSystemPrefix(name: string): string {
    return removeSystemPrefix(name)
  }
  //#endregion
}
